name: ci php

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2, 8.3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, fileinfo, mysql, redis
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-lock

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-scripts

      - name: Run PHP Coding Standards, Static Analysis and Unit Tests
        run: |
          echo "Running in $dir"
          cd "$dir"
          composer install --no-interaction --prefer-dist --no-progress
          composer run check-cs
          composer run analyze
          composer run test